### ISSUE TITLE
SE-net module placement in inception resnet

### ISSUE THREAD

**Issue by sp-ananth** [kobiso/SENet-tensorflow-slim#2]
Hi there,
I notice that the original paper says that for resnet, the SE-block is applied to "The non-identity branch  of the residual nodule". And in the inception network after each inception block.

In you inception-resnet implementation, you seem to have applied the SE module to the identity branch of each block instead. (i.e) to the net variable rather than the (up*scale) variable. 

Is there any reason for this? Did this configuration work for you?

**Comment by kobiso** [comment]
@sp-ananth 
I just checked my code and what you said is right.
I meant to put SE module on the non-identity branch of the residual module, but I mistakenly put SE module to the identity branch.
Thank you for pointing out my mistake 👍 
I will revised the code and upload it soon.

**Comment by kobiso** [comment]
Revising the SE module placement in Inception_resnet_v2 is completed: https://github.com/kobiso/SENet-tensorflow-slim/commit/51b6d27b57498ce163d3b21acdb45292d1857619
